name: Songdo3DMap
options:
  bundleIdPrefix: com.songdo
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    SWIFT_OBJC_BRIDGING_HEADER: "Songdo3DMap/Core/Renderer/Shaders/Songdo3DMap-Bridging-Header.h"
    MTL_HEADER_SEARCH_PATHS: "$(SRCROOT)/Songdo3DMap/Core/Renderer/Shaders"

targets:
  Songdo3DMap:
    type: application
    platform: iOS
    sources:
      - path: Songdo3DMap
        excludes:
          - "**/.DS_Store"
          - "Preprocessing/**"
        compilerFlags:
          - path: "Core/Renderer/Shaders/*.metal"
            flags: []
      - path: Songdo3DMap/Resources/MapData
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.songdo.map3d
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        INFOPLIST_KEY_CFBundleDisplayName: "송도 3D 지도"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.navigation"
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "현재 위치를 지도에 표시하기 위해 위치 정보가 필요합니다."
        # Metal 설정
        MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
        MTL_FAST_MATH: YES
        # GPU Frame Capture
        METAL_DEVICE_WRAPPER_TYPE: 1
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
          GCC_PREPROCESSOR_DEFINITIONS:
            - DEBUG=1
            - $(inherited)
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          MTL_ENABLE_DEBUG_INFO: NO
    dependencies: []
    preBuildScripts: []
    postBuildScripts: []

schemes:
  Songdo3DMap:
    build:
      targets:
        Songdo3DMap: all
    run:
      config: Debug
      commandLineArguments:
        "-MTL_DEBUG_LAYER": true
        "-MTL_SHADER_VALIDATION": true
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
